; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; Freenove ESP32 3.5 and 4in LCDs
; https://docs.freenove.com/projects/fnk0103/en/latest/
[env:freenove_esp32_lcd]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

; Enable PSRAM (Critical for 4" LCD UI frameworks like LVGL)
build_flags =
  -DBOARD_HAS_PSRAM

; Configure PSRAM and Flash Memory Type
; Most 4" Freenove boards use QIO/OPI mode for PSRAM and QIO for Flash
;board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB

; Use the UART port for serial monitor and programming.
[env:esp32-s3-devkitc-1-uart]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0
monitor_speed = 115200

; This board has two USB ports. If both are plugged in,
; we need to specify which port to use based on the USB VID/PID.
;upload_port = hwid:1A86:55D3
;monitor_port = hwid:1A86:55D3
upload_port = COM15
monitor_port = COM15
