; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; Freenove ESP32 3.5 and 4in LCDs
; https://docs.freenove.com/projects/fnk0103/en/latest/
[env:freenove_esp32_lcd]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

; Enable PSRAM (Critical for 4" LCD UI frameworks like LVGL)
build_flags =
  -DBOARD_HAS_PSRAM

; Configure PSRAM and Flash Memory Type
; Most 4" Freenove boards use QIO/OPI mode for PSRAM and QIO for Flash
;board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi   ; OPI (octal) PSRAM on N16R8; use qio_qspi for QSPI parts
build_flags =
    -DBOARD_HAS_PSRAM
monitor_speed = 115200

; This board has two USB ports, one for programming and one for serial monitor. The default is the programming port, which is used for uploading.
; The serial monitor port must be specified explicitly.
upload_port = COM4
monitor_port = COM13
