; Freenove ESP32 3.5 and 4in LCDs
; https://docs.freenove.com/projects/fnk0103/en/latest/
[env:freenove_esp32_lcd]
extends = arduino_base
board = freenove_esp32_wrover
board_build.filesystem = littlefs

; Configure PSRAM and Flash Memory Type
; Most 4" Freenove boards use QIO/OPI mode for PSRAM and QIO for Flash
;board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB

; Enable PSRAM (Critical for 4" LCD UI frameworks like LVGL)
build_flags =
    -DBOARD_HAS_PSRAM
    -DSTATUS_LED_PIN=22
    -DSTATUS_LED_IS_RGB=0
