; Uses the UART port for serial monitor and programming.
[env:esp32-s3-devkitc-1-uart]
extends = arduino_base
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DSTATUS_LED_PIN=47
    -DSTATUS_LED_IS_RGB=1
